// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwSVzcOqvSEUAQFMC__pLHn9Z-AIMj84',
    appId: '1:434501860224:web:6700b8c61413f258561f65',
    messagingSenderId: '434501860224',
    projectId: 'lvs-interview',
    authDomain: 'lvs-interview.firebaseapp.com',
    storageBucket: 'lvs-interview.firebasestorage.app',
    measurementId: 'G-VR2DHRTPNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_B0Tmp5VFt4_HNNZiQPeKMEORLJoB_OQ',
    appId: '1:434501860224:android:0deccea78428ca02561f65',
    messagingSenderId: '434501860224',
    projectId: 'lvs-interview',
    storageBucket: 'lvs-interview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2OG4aqSLTWK2ESuFNYSxQt1Vdrm4WcQ',
    appId: '1:434501860224:ios:595cc3dfc568d285561f65',
    messagingSenderId: '434501860224',
    projectId: 'lvs-interview',
    storageBucket: 'lvs-interview.firebasestorage.app',
    iosClientId: '434501860224-jvkdtr3tbe0d8ggqp4n15d70sipha74l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lvsinterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm2OG4aqSLTWK2ESuFNYSxQt1Vdrm4WcQ',
    appId: '1:434501860224:ios:595cc3dfc568d285561f65',
    messagingSenderId: '434501860224',
    projectId: 'lvs-interview',
    storageBucket: 'lvs-interview.firebasestorage.app',
    iosClientId: '434501860224-jvkdtr3tbe0d8ggqp4n15d70sipha74l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lvsinterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLwSVzcOqvSEUAQFMC__pLHn9Z-AIMj84',
    appId: '1:434501860224:web:31be4bc6c17eabf8561f65',
    messagingSenderId: '434501860224',
    projectId: 'lvs-interview',
    authDomain: 'lvs-interview.firebaseapp.com',
    storageBucket: 'lvs-interview.firebasestorage.app',
    measurementId: 'G-XM1YM8N3S8',
  );
}
